### ISSUE TITLE
can't create databases with sql parameter for import

### ISSUE THREAD

**Issue by vmpr** [puppetlabs/puppetlabs-mysql#1565]
## Describe the Bug
I would like to create a database and import a defined SQL dump via Hiera, but I get an error message instead
## Expected Behavior
create database like the others but import an SQL dump

## Steps to Reproduce
Hiera config: normal databases are created but the one with the SQL parameter throws an error
```
# databases
mysql::server::databases:
  test123:
    ensure: present
  phpmyadmin:
    ensure: present
    sql:
      - '/var/www/phpmyadmin/sql/create_tables.sql'
```
error on puppetrun:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'sql' (file: /etc/puppetlabs/code/environments/dev/modules/external/mysql/manifests/server/providers.pp, line: 9) on Mysql_database[phpmyadmin] (file: /etc/puppetlabs/code/environments/dev/modules/external/mysql/manifests/server/providers.pp, line: 9) on node XXX
```
## Environment
 - Platform Debian 11

## Additional Context
from how I understood the code it should create the resource and use the parameters which are defined for MySQL::db https://github.com/puppetlabs/puppetlabs-mysql/blob/c029062f7d7a3814f507ca5bdb1361944af345ea/manifests/db.pp#L101
